POST http://localhost:3001/api/telefono
Content-Type: application/json

{
    "name": "Lazara",
    "telefono": "53052129"
}

###
PUT http://localhost:3001/api/telefono/62e557939414a226fd4bba5a
Content-Type: application/json

{
    "name": "Lazara",
    "telefono": "53052129"
}